- name: install nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

