- name: Copy cart service
  ansible.builtin.copy:
    src: cart.service
    dest: /etc/systemd/system/cart.service

- name: deamon realod and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable cart
  ansible.builtin.service:
    name: cart
    state: started
    enabled: yes
