- name: Copy payment service
  ansible.builtin.copy:
    src: payment.service
    dest: /etc/systemd/system/payment.service

- name: deamon realod and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable payment
  ansible.builtin.service:
    name: shipping
    state: started
    enabled: yes
