- name: Copy user service
  ansible.builtin.copy:
    src: user.service
    dest: /etc/systemd/system/user.service

- name: deamon realod and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable user
  ansible.builtin.service:
    name: user
    state: started
    enabled: yes
